GET http://localhost:3000

###
GET http://localhost:3000/login

###
GET http://localhost:3000/register

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "user4",
    "password": "pass"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user3",
    "password": "pass"
}

###
POST http://localhost:3000/logout

###
POST http://localhost:3000/entry
Content-Type: application/json

{
    "label": "another entry"
}

###
GET http://localhost:3000/user/

###
POST http://localhost:3000/entry/:entryId
Content-Type: application/json

{
    "id": "61c49cd75b9de7dfc50ac551",
    "fieldLabel": "label",
    "fieldContent": "content"
}