GET http://localhost:3000

###
GET http://localhost:3000/login

###
GET http://localhost:3000/register

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "user2",
    "password": "pass"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2",
    "password": "pass"
}

###
POST http://localhost:3000/logout

###
POST http://localhost:3000/entry
Content-Type: application/json

{
    "label": "second entry"
}

###
GET http://localhost:3000/user/:id
Content-Type: application/json

{
    "id": "61c401dd85ea4add7764f835"
}

###
POST http://localhost:3000/entry/:entryId
Content-Type: application/json

{
    "id": "61c401dd85ea4add7764f835",
    "entryId": "61c4052a52a0745f4947c068",
    "fieldLabel": "a new label",
    "fieldContent": "some content"
}